dist: bionic
sudo: false
language: cpp

matrix:
  include:
    - os: linux
      env: CONFIGURATION=Debug
    - os: linux
      env: CONFIGURATION=Release
    - os: osx
      env: CONFIGURATION=Debug
    - os: osx
      env: CONFIGURATION=Release

script:
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=$CONFIGURATION -Dbuild_tests=ON ..
    - cmake --build . -j 4
    - ctest --verbose

notifications:
  email:
    on_success: change
    on_failure: change
