version: "{build}"

os: Visual Studio 2017

platform: 
  - Win32
  - x64

configuration:
  - Debug
  - Release

init:
  - cmd: cmake --version
  - cmd: msbuild /version

clone_folder: C:\projects\gcl

before_build:
  - cmd: cd C:\projects\gcl
  - cmd: md build
  - cmd: cd build
  - cmd: if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=Visual Studio 15 2017
  - cmd: if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=Visual Studio 15 2017 Win64
  - cmd: cmake -G "%CMAKE_GENERATOR_NAME%" ..

build:
  project: C:\projects\gcl\build\gcl.sln
  parallel: true

install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive

test_script:
  - cmd: cd C:\projects\gcl\build
  - cmd: ctest --verbose
