name: gcl
on: [push]
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        config: [Debug, Release]
        asan: [ON, OFF]
        tsan: [ON, OFF]
        exclude:
          - asan: ON
            tsan: ON
          - asan: ON
            os: windows-latest
          - tsan: ON
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: use msvc
        uses: ilammy/msvc-dev-cmd@v1
      - name: run tests
        run: |
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.config }} -Dgcl_build_tests=ON -Dgcl_enable_asan=${{ matrix.asan }} -Dgcl_enable_tsan=${{ matrix.tsan }} .
          cmake --build . -j 4
          ctest --verbose
