name: gcl tests
on: [push]
jobs:
  build-on-linux:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: run debug
        run: ./test.sh Debug
      - name: run release
        run: ./test.sh Release
  build-on-mac:
    runs-on: macos-11
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: run debug
        run: ./test.sh Debug
      - name: run release
        run: ./test.sh Release
  build-on-windows:
    runs-on: windows-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: use msvc
        uses: ilammy/msvc-dev-cmd@v1
      - name: run debug
        run: |
          cmake -DCMAKE_BUILD_TYPE=Debug -Dgcl_build_tests=ON .
          cmake --build .
          ctest --verbose
