name: gcl
on: [push]
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-11, windows-latest]
        config: [Debug, Release]
        asan: [ON, OFF]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: use msvc
        uses: ilammy/msvc-dev-cmd@v1
      - name: run tests
        run: |
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.config }} -Dgcl_build_tests=ON -Dgcl_enable_asan=${{ matrix.asan }} .
          cmake --build . -j 4
          ctest --verbose
