name: gcl tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: run debug
        run: ./test.sh Debug
      - name: run release
        run: ./test.sh Release

